### ISSUE TITLE
Metadata update failed: Cannot read properties of undefined (reading 'filter')

### ISSUE THREAD

**Issue by jackhric** [bonukai/MediaTracker#548]
Currently running MediaTracker (unstable), I keep running into logs that state that MediaTracker failed to update item metadata.
Here's an attempt to update metadata for Adventure Time using the "Update Metadata" button present on a TV item screen.
Anyone else having this issue?
```
info:  Updating metadata for 3 items

info:  Updating: Adventure Time

error: TypeError: Cannot read properties of undefined (reading 'filter')

info:  Updated 0 items

error: Failed to update 1 item
```

**Comment by ikidd** [comment]
I see this as well.  Installed recently and logs show this on every show update.

**Comment by lyz-code** [comment]
I'm seeing the same error with [`The Legend of Vox Machina`](https://www.themoviedb.org/tv/135934-the-legend-of-vox-machina)

**Comment by sporked-thm** [comment]
Checking in.  Using the most recent copy as of 2024-12-04.  

In my logs: 
`12/15/2024, 1:33:27 PM error: TypeError: Cannot read properties of undefined (reading 'filter')
    at sendNotifications (/usr/local/lib/node_modules/mediatracker/src/updateMetadata.ts:216:8)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at updateMediaItem (/usr/local/lib/node_modules/mediatracker/src/updateMetadata.ts:366:9)
    at Array.<anonymous> (/usr/local/lib/node_modules/mediatracker/src/controllers/item.ts:66:5)`

Since many updates before, and some updates after work, and this issue is sporadic, is there some sort of commonality here.   How can we duplicate the data retrieve operation (read: manually run whatever) that this routine is using to verify the legitimacy of this data?
